# More info on config here: https://golangci-lint.run/usage/configuration/#config-file

version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - revive
    - staticcheck
    - unused
    - wsl
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: G404
      - path: (.+)\.go$
        text: exported func .* returns unexported type .*, which can be annoying to use
      - path: (.+)\.go$
        text: should have a package comment, unless it's in another file for this package
      - path: (.+)\.go$
        text: don't use an underscore in package name
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: should check returned error before deferring
    paths:
      - \.pb\.go$
      - \.pb\.goclay\.go$
      - \.pb\.gw\.go$
      - bin
      - builtin$
      - examples$
      - test
      - third_party$
      - tmp
      - var
      - vendor
issues:
  fix: true
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - \.pb\.go$
      - \.pb\.goclay\.go$
      - \.pb\.gw\.go$
      - bin
      - builtin$
      - examples$
      - test
      - third_party$
      - tmp
      - var
      - vendor
