// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/music_client_mock.go -exclude_interfaces=Service -mock_names=musicClient=MockMusicClient
//

// Package mock_yandex is a generated GoMock package.
package mock_yandex

import (
	context "context"
	reflect "reflect"

	yandex "github.com/oshokin/zvuk-grabber/internal/client/yandex"
	model "github.com/oshokin/zvuk-grabber/internal/client/yandex/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMusicClient is a mock of musicClient interface.
type MockMusicClient struct {
	ctrl     *gomock.Controller
	recorder *MockMusicClientMockRecorder
	isgomock struct{}
}

// MockMusicClientMockRecorder is the mock recorder for MockMusicClient.
type MockMusicClientMockRecorder struct {
	mock *MockMusicClient
}

// NewMockMusicClient creates a new mock instance.
func NewMockMusicClient(ctrl *gomock.Controller) *MockMusicClient {
	mock := &MockMusicClient{ctrl: ctrl}
	mock.recorder = &MockMusicClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMusicClient) EXPECT() *MockMusicClientMockRecorder {
	return m.recorder
}

// AlbumWithTracks mocks base method.
func (m *MockMusicClient) AlbumWithTracks(ctx context.Context, id string) (*model.Album, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlbumWithTracks", ctx, id)
	ret0, _ := ret[0].(*model.Album)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlbumWithTracks indicates an expected call of AlbumWithTracks.
func (mr *MockMusicClientMockRecorder) AlbumWithTracks(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlbumWithTracks", reflect.TypeOf((*MockMusicClient)(nil).AlbumWithTracks), ctx, id)
}

// DownloadCoverBytes mocks base method.
func (m *MockMusicClient) DownloadCoverBytes(ctx context.Context, rawURL string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCoverBytes", ctx, rawURL)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadCoverBytes indicates an expected call of DownloadCoverBytes.
func (mr *MockMusicClientMockRecorder) DownloadCoverBytes(ctx, rawURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCoverBytes", reflect.TypeOf((*MockMusicClient)(nil).DownloadCoverBytes), ctx, rawURL)
}

// DownloadFLACBytes mocks base method.
func (m *MockMusicClient) DownloadFLACBytes(ctx context.Context, trackID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFLACBytes", ctx, trackID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFLACBytes indicates an expected call of DownloadFLACBytes.
func (mr *MockMusicClientMockRecorder) DownloadFLACBytes(ctx, trackID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFLACBytes", reflect.TypeOf((*MockMusicClient)(nil).DownloadFLACBytes), ctx, trackID)
}

// OpenAudio mocks base method.
func (m *MockMusicClient) OpenAudio(ctx context.Context, rawURL string) (*yandex.RemoteFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenAudio", ctx, rawURL)
	ret0, _ := ret[0].(*yandex.RemoteFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenAudio indicates an expected call of OpenAudio.
func (mr *MockMusicClientMockRecorder) OpenAudio(ctx, rawURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenAudio", reflect.TypeOf((*MockMusicClient)(nil).OpenAudio), ctx, rawURL)
}

// PlaylistByUUID mocks base method.
func (m *MockMusicClient) PlaylistByUUID(ctx context.Context, id string) (*model.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaylistByUUID", ctx, id)
	ret0, _ := ret[0].(*model.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaylistByUUID indicates an expected call of PlaylistByUUID.
func (mr *MockMusicClientMockRecorder) PlaylistByUUID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaylistByUUID", reflect.TypeOf((*MockMusicClient)(nil).PlaylistByUUID), ctx, id)
}

// ResolveMP3Link mocks base method.
func (m *MockMusicClient) ResolveMP3Link(ctx context.Context, trackID string, preferredQuality uint8) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveMP3Link", ctx, trackID, preferredQuality)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResolveMP3Link indicates an expected call of ResolveMP3Link.
func (mr *MockMusicClientMockRecorder) ResolveMP3Link(ctx, trackID, preferredQuality any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveMP3Link", reflect.TypeOf((*MockMusicClient)(nil).ResolveMP3Link), ctx, trackID, preferredQuality)
}

// TrackInfo mocks base method.
func (m *MockMusicClient) TrackInfo(ctx context.Context, id string) (*model.Track, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackInfo", ctx, id)
	ret0, _ := ret[0].(*model.Track)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackInfo indicates an expected call of TrackInfo.
func (mr *MockMusicClientMockRecorder) TrackInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackInfo", reflect.TypeOf((*MockMusicClient)(nil).TrackInfo), ctx, id)
}

// TrackLyrics mocks base method.
func (m *MockMusicClient) TrackLyrics(ctx context.Context, id string) (*model.TrackLyrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackLyrics", ctx, id)
	ret0, _ := ret[0].(*model.TrackLyrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackLyrics indicates an expected call of TrackLyrics.
func (mr *MockMusicClientMockRecorder) TrackLyrics(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackLyrics", reflect.TypeOf((*MockMusicClient)(nil).TrackLyrics), ctx, id)
}

// UsersPlaylist mocks base method.
func (m *MockMusicClient) UsersPlaylist(ctx context.Context, id, username string) (*model.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsersPlaylist", ctx, id, username)
	ret0, _ := ret[0].(*model.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UsersPlaylist indicates an expected call of UsersPlaylist.
func (mr *MockMusicClientMockRecorder) UsersPlaylist(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsersPlaylist", reflect.TypeOf((*MockMusicClient)(nil).UsersPlaylist), ctx, id, username)
}
