// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go
//

// Package mock_zvuk is a generated GoMock package.
package mock_zvuk

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DownloadURLs mocks base method.
func (m *MockService) DownloadURLs(ctx context.Context, urls []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadURLs", ctx, urls)
}

// DownloadURLs indicates an expected call of DownloadURLs.
func (mr *MockServiceMockRecorder) DownloadURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadURLs", reflect.TypeOf((*MockService)(nil).DownloadURLs), ctx, urls)
}
