// Code generated by MockGen. DO NOT EDIT.
// Source: template_manager.go
//
// Generated by this command:
//
//	mockgen -source=template_manager.go -destination=mocks/template_manager_mock.go
//

// Package mock_zvuk is a generated GoMock package.
package mock_zvuk

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateManager is a mock of TemplateManager interface.
type MockTemplateManager struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateManagerMockRecorder
	isgomock struct{}
}

// MockTemplateManagerMockRecorder is the mock recorder for MockTemplateManager.
type MockTemplateManagerMockRecorder struct {
	mock *MockTemplateManager
}

// NewMockTemplateManager creates a new mock instance.
func NewMockTemplateManager(ctrl *gomock.Controller) *MockTemplateManager {
	mock := &MockTemplateManager{ctrl: ctrl}
	mock.recorder = &MockTemplateManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateManager) EXPECT() *MockTemplateManagerMockRecorder {
	return m.recorder
}

// GetAlbumFolderName mocks base method.
func (m *MockTemplateManager) GetAlbumFolderName(ctx context.Context, tags map[string]string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAlbumFolderName", ctx, tags)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAlbumFolderName indicates an expected call of GetAlbumFolderName.
func (mr *MockTemplateManagerMockRecorder) GetAlbumFolderName(ctx, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAlbumFolderName", reflect.TypeOf((*MockTemplateManager)(nil).GetAlbumFolderName), ctx, tags)
}

// GetTrackFilename mocks base method.
func (m *MockTemplateManager) GetTrackFilename(ctx context.Context, isPlaylist bool, trackTags map[string]string, tracksCount int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackFilename", ctx, isPlaylist, trackTags, tracksCount)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTrackFilename indicates an expected call of GetTrackFilename.
func (mr *MockTemplateManagerMockRecorder) GetTrackFilename(ctx, isPlaylist, trackTags, tracksCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackFilename", reflect.TypeOf((*MockTemplateManager)(nil).GetTrackFilename), ctx, isPlaylist, trackTags, tracksCount)
}
