// Code generated by MockGen. DO NOT EDIT.
// Source: url_processor.go

// Package mock_zvuk is a generated GoMock package.
package mock_zvuk

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	zvuk "github.com/oshokin/zvuk-grabber/internal/service/zvuk"
)

// MockURLProcessor is a mock of URLProcessor interface.
type MockURLProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockURLProcessorMockRecorder
}

// MockURLProcessorMockRecorder is the mock recorder for MockURLProcessor.
type MockURLProcessorMockRecorder struct {
	mock *MockURLProcessor
}

// NewMockURLProcessor creates a new mock instance.
func NewMockURLProcessor(ctrl *gomock.Controller) *MockURLProcessor {
	mock := &MockURLProcessor{ctrl: ctrl}
	mock.recorder = &MockURLProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLProcessor) EXPECT() *MockURLProcessorMockRecorder {
	return m.recorder
}

// DeduplicateDownloadItems mocks base method.
func (m *MockURLProcessor) DeduplicateDownloadItems(items []*zvuk.DownloadItem) []*zvuk.DownloadItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeduplicateDownloadItems", items)
	ret0, _ := ret[0].([]*zvuk.DownloadItem)
	return ret0
}

// DeduplicateDownloadItems indicates an expected call of DeduplicateDownloadItems.
func (mr *MockURLProcessorMockRecorder) DeduplicateDownloadItems(items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeduplicateDownloadItems", reflect.TypeOf((*MockURLProcessor)(nil).DeduplicateDownloadItems), items)
}

// ExtractDownloadItems mocks base method.
func (m *MockURLProcessor) ExtractDownloadItems(ctx context.Context, urls []string) (*zvuk.ExtractDownloadItemsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractDownloadItems", ctx, urls)
	ret0, _ := ret[0].(*zvuk.ExtractDownloadItemsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractDownloadItems indicates an expected call of ExtractDownloadItems.
func (mr *MockURLProcessorMockRecorder) ExtractDownloadItems(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractDownloadItems", reflect.TypeOf((*MockURLProcessor)(nil).ExtractDownloadItems), ctx, urls)
}
