# This workflow builds, tests, and releases a Go project using GitHub Actions.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Release

# Trigger conditions for the workflow
on:
  push:
    branches: ["master"] # Trigger on pushes to the 'master' branch
    tags:
      - "v*" # Trigger on tags starting with 'v' (e.g., v1.0.0)
  pull_request:
    branches: ["master"] # Trigger on pull requests targeting the 'master' branch

# Permissions required for the workflow
permissions:
  contents: write # Allow writing to the repository (e.g., for creating releases)

# Jobs define the tasks to be executed
jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    if: startsWith(github.ref, 'refs/tags/v') # Only run this job for tags starting with 'v'

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4
        with:
          # Fetch the entire Git history to allow GoReleaser to access older tags
          fetch-depth: 0

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable # Use the latest stable version of Go

      # Step 3: Build the Go project
      - name: Build
        run: go build -v ./... # Build the project with verbose output

      # Step 4: Run tests for the Go project
      - name: Test
        run: go test -v ./... # Run tests with verbose output

      # Step 5: Create a release using GoReleaser
      - name: Release
        uses: goreleaser/goreleaser-action@v6 # Use the GoReleaser GitHub Action
        with:
          args: release --clean # Run GoReleaser with the 'release --clean' command
        env:
          # Authenticate with GitHub using the default GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
